import React, { useState } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Radio from '@mui/material/Radio';
import RadioGroup from '@mui/material/RadioGroup';
import FormControlLabel from '@mui/material/FormControlLabel';
import FormControl from '@mui/material/FormControl';
import Problem1 from "./components/Problem1";
import Problem2 from "./components/Problem2";


export default function Home() {
  const [selectedProblem, setSelectedProblem] = useState('1');

  const handleSelectProblem = (problemNum) => {
    setSelectedProblem(problemNum)
  };

  return (
    <>
      <Head>
        <title>Courier Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Coding Challenge Courier Service
        </h1>
        <p className={styles.centerContainer} style={{ fontSize: 24 }} data-testid='radio'>Select problem:</p>
        <FormControl className={styles.centerContainer}>
          <RadioGroup
            row
            aria-labelledby="demo-form-control-label-placement"
            name="position"
            defaultValue="top"
          >
            <FormControlLabel
              value="top"
              control={<Radio onClick={() => { handleSelectProblem('1') }} inputProps={{ "data-testid": "radio-1" }} />}
              label="Problem 1"

            />
            <FormControlLabel
              value="start"
              control={<Radio onClick={() => { handleSelectProblem('2') }} inputProps={{ "data-testid": "radio-2" }} />}
              label="Problem 2"

            />
          </RadioGroup>
        </FormControl>

        <div className={styles.centerContainer}>
          {selectedProblem === '1' && (
            <Problem1 />
          )}
          {selectedProblem === '2' && (
            <Problem2 />
          )}

        </div>
      </main>
    </>
  )
}